### ISSUE TITLE
 Fatal error: Call to undefined function bp_new_simple_blog_post_form() 

### ISSUE THREAD

**Issue by Thwar** [sbrajesh/bp-simple-front-end-post#8]
Wordpress Noob here. I can't understand why the function is not being found. I am using the example code: add_action( 'bp_init', 'my_post_form', 4 ); ---> this is calling bp_new_simple_blog_post_form() .

My understanding is that bp_init should initialize all bp functions, so there should be any undefined functions? 

What am I doing wrong?

Thanks in advance!

Error details:

Fatal error: Call to undefined function bp_new_simple_blog_post_form() in /home/content/65/11231665/html/diasporahomecoming.com/site/wp-content/themes/klein-child/functions.php on line 38

**Comment by sbrajesh** [comment]
Hi Thwar,
Do you have this plugin installed and activated? The functions comes for this plugin, so this plugin should be active to make it work.

**Comment by Thwar** [comment]
Hi Sbrajesh , 

it is active. I made sure of it using this code: 
if ( is_plugin_active( 'bp-simple-front-end-post/bp-simple-front-end-post.php') ) {
  //plugin is activated
echo "plugin is activated";
} 
else
{
echo "plugin is NOT activated";
}

I even tried to deactivate it manually and reactivate it.
Thanks

**Comment by sbrajesh** [comment]
Hi,
I checked the plugin now and I guess I know why it is happening. Try to put a condition like 

```
if (is_admin() ) {
return ;
}

```

In the my_post_form top.

You can think of it as my mistake or over optimization as I do not load any of this plugin file in admin and bp_init will run irrespective of front end/admin.

Hope that helps.

**Comment by Thwar** [comment]
Looks like it worked. Great. Thanks!

Here is how I put down the code:

function my_post_form() {
if (is_admin() ) {
return ;
}
..........
}

**Comment by sbrajesh** [comment]
Glad that it worked. Yes, That is the right way :)
