### ISSUE TITLE
Toolbar bug

### ISSUE THREAD

**Issue by Ruddernation-Designs** [sbrajesh/bp-simple-front-end-post#9]
~Hello @sbrajesh 
It is showing `+New(Media)` in the toolbar on front end for logged out users,
I've tested this by deactivating `BP Simple Front End Post` and it disappears,
I'm now currently hiding the toolbar for logged out users,
Also this only shows on Buddypress pages, `activity/members/groups/register/activate`
![toolbar](https://cloud.githubusercontent.com/assets/7717199/14329026/d701373c-fc39-11e5-94e7-ae29207c64bc.jpg)

**Comment by sbrajesh** [comment]
Hi Ben,
Thank you. It may be a bug. Please allow me to check today and will update accordingly.

Thank you
Brajesh

**Comment by sbrajesh** [comment]
Sorry that I could not reply back. Is fixed now. Closing.

**Comment by Ruddernation-Designs** [comment]
Thank you @sbrajesh
